### PR TITLE
Documentation: several fixes

### PR DESCRIPTION
**Pull request by romajke**

### CODE REVIEW

**Comment by romajke** [comment]
Page: http://rtsisyk.github.io/luafun/reducing.html#fun.every
Screenshot: http://img.parcsis.net/i/9de8b9eecc36d89cb47eb73cce1d0985.png

**Comment by romajke** [comment]
Page: http://rtsisyk.github.io/luafun/reducing.html#fun.min
Screenshot: http://img.parcsis.net/i/a99bbd5dbd0e4a3d0b4e5ad11026aca2.png

**Comment by romajke** [comment]
Page: http://rtsisyk.github.io/luafun/under_the_hood.html#iterations
Screenshot: http://img.parcsis.net/i/0c083c7a344636fd16b6d3dbe949286f.png

**Comment by rtsisyk** [comment]
Merged. Thanks!
I'll regenerate gh-pages too.

**Pull request merged**
